//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotslogsExportProcessor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%USERPROFILE%\\Documents\\HOTSLogsExport")]
        public string HotsLogsExportPath {
            get {
                return ((string)(this["HotsLogsExportPath"]));
            }
            set {
                this["HotsLogsExportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TeamLeague")]
        public string BaseWinrateGameMode {
            get {
                return ((string)(this["BaseWinrateGameMode"]));
            }
            set {
                this["BaseWinrateGameMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int BaseWinrateNumberOfDays {
            get {
                return ((int)(this["BaseWinrateNumberOfDays"]));
            }
            set {
                this["BaseWinrateNumberOfDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuickMatch")]
        public string AdjustmentsGameMode {
            get {
                return ((string)(this["AdjustmentsGameMode"]));
            }
            set {
                this["AdjustmentsGameMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AdjustmentsNumberOfDays {
            get {
                return ((int)(this["AdjustmentsNumberOfDays"]));
            }
            set {
                this["AdjustmentsNumberOfDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%USERPROFILE%\\Documents\\HotsDraftData.json")]
        public string ExtractDestinationPath {
            get {
                return ((string)(this["ExtractDestinationPath"]));
            }
            set {
                this["ExtractDestinationPath"] = value;
            }
        }
    }
}
